## git                                                                                                                                                                                                    
alias gst='git status'
alias gcm='git commit -m'
alias gco='git checkout'
alias gpo='git push origin'
alias gfa='git fetch --all'
alias gpull='git pull'
alias gmo='git merge origin'
alias gba='git branch -a'
alias gcb='git checkout -b'
alias gbd='git branch -d'
alias glog='git log'
